import type { DayOfWeek, SingleMealType, TiffinDietType, TiffinMealTier } from "@tbc/shared-types";

/**
 * One-time snapshot of GG Tiffin's single-meal weekly rotation, computed from the business's
 * real curated menu that used to live as hardcoded tables/cascading-override logic directly in
 * the codebase (singleMealMenu.ts's old `getSingleMealDish`, tiffinSchedule.ts's old `dishForDay`,
 * and the mobile app's own duplicate of both). That logic is gone now — every (tier, dietType,
 * mealType, dayOfWeek) slot is its own row in the `TiffinDish` collection, independently editable
 * from the admin panel. This file only exists to seed that collection's initial state so day one
 * looks identical to what the app already served; it is never imported by any runtime code path.
 *
 * Regenerated by walking every valid combination through the old resolution functions and image
 * lookup tables before they were deleted — not retyped by hand, so it can't have transcription
 * errors relative to what was actually live.
 */
export interface TiffinDishSeedRow {
  tier: TiffinMealTier;
  dietType: TiffinDietType;
  mealType: SingleMealType;
  dayOfWeek: DayOfWeek;
  dishName: string;
  /** Resolved to a full URL (via seed.ts's own tiffinImageUrl helper) at seed time. */
  imageSlug: string;
  /** Per-dish price override — when set, takes precedence over the shared (tier, mealType)
   * TiffinMealPrice slot price. Unset for dishes not yet individually priced by the admin. */
  price?: number;
  hasAddOns: boolean;
  riceSubstitute: "rice" | "pulao";
  extraAddOnName?: string;
}

export const TIFFIN_DISH_SEED_DATA: TiffinDishSeedRow[] = [
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Poha", imageSlug: "poha", price: 59, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Upma", imageSlug: "upma", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Sandwich", imageSlug: "sandwich", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Puri with Chole & Achar", imageSlug: "puri-chola", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer", price: 109, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  // Sunday dinner is a biryani special across every tier (see the non-veg row below too) — a
  // complete one-box meal, not the usual rice/roti/curry combo, so hasAddOns is false here.
  // Reuses The Biryani Lane's own real "Veg Biryani" photo (same dish, different brand).
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Veg Biryani", imageSlug: "veg-biryani", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Poha", imageSlug: "poha", price: 59, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Bread Omelette", imageSlug: "bread-omelete", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Chicken Sandwich", imageSlug: "sandwich", price: 89, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Puri with Chole & Achar", imageSlug: "puri-chola", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Fish Curry", imageSlug: "fish-curry", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Fish piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Egg Curry", imageSlug: "egg-curry", price: 69, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Chicken Curry", imageSlug: "chicken-curry", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  // Sunday special, same as veg above — reuses The Biryani Lane's own real "Chicken Biryani" photo.
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Chicken Biryani", imageSlug: "chicken-biryani", price: 99, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala-mini", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer-mini", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo-mini", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Veg Biryani", imageSlug: "veg-biryani", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala-mini", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma-mini", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Fish Curry", imageSlug: "fish-curry-mini", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Fish piece" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", price: 69, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Egg Curry", imageSlug: "egg-curry-mini", price: 69, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo-mini", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Chicken Curry", imageSlug: "chicken-curry-mini", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Chicken Biryani", imageSlug: "chicken-biryani", price: 99, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Poha", imageSlug: "poha", price: 59, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Upma", imageSlug: "upma", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Sandwich", imageSlug: "sandwich", price: 69, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Idli / Dosa with Sambar & Chutney", imageSlug: "idli-with-sambar-and-chutney", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Paneer Butter Masala", imageSlug: "paneer-butter-masala-and-pulao", price: 119, hasAddOns: true, riceSubstitute: "pulao" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer", price: 109, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Veg Biryani", imageSlug: "veg-biryani", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Poha", imageSlug: "poha", price: 59, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Bread Omelette", imageSlug: "bread-omelete", price: 49, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Chicken Sandwich", imageSlug: "sandwich", price: 89, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Idli / Dosa with Sambar & Chutney", imageSlug: "idli-with-sambar-and-chutney", price: 79, hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Mutton Curry", imageSlug: "mutton-and-pulao", price: 149, hasAddOns: true, riceSubstitute: "pulao", extraAddOnName: "Mutton piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Fish Curry", imageSlug: "fish-curry", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Fish piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", price: 79, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Egg Curry", imageSlug: "egg-curry", price: 69, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", price: 89, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Chicken Curry", imageSlug: "chicken-curry", price: 89, hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", price: 99, hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Chicken Biryani", imageSlug: "chicken-biryani", price: 99, hasAddOns: false, riceSubstitute: "rice" },
];

/** The named add-ons' shared flat prices — same value wherever the add-on is offered. */
export const TIFFIN_ADD_ON_PRICE_SEED_DATA: { name: string; price: number }[] = [
  { name: "Rice", price: 20 },
  { name: "Roti", price: 10 },
  { name: "Daal", price: 20 },
  { name: "Paratha", price: 15 },
  { name: "Pulao", price: 25 },
  { name: "Fish piece", price: 45 },
  { name: "Egg piece", price: 15 },
  { name: "Chicken piece", price: 40 },
  { name: "Mutton piece", price: 60 },
  // Generic "top up the same veg dish" add-on — its display name is synthesized per-dish at
  // resolution time as "Extra {dishName}"; this row just holds its shared flat price.
  { name: "Extra Portion", price: 30 },
];
