import type { DayOfWeek, SingleMealType, TiffinDietType, TiffinMealTier } from "@tbc/shared-types";

/**
 * One-time snapshot of GG Tiffin's single-meal weekly rotation, computed from the business's
 * real curated menu that used to live as hardcoded tables/cascading-override logic directly in
 * the codebase (singleMealMenu.ts's old `getSingleMealDish`, tiffinSchedule.ts's old `dishForDay`,
 * and the mobile app's own duplicate of both). That logic is gone now — every (tier, dietType,
 * mealType, dayOfWeek) slot is its own row in the `TiffinDish` collection, independently editable
 * from the admin panel. This file only exists to seed that collection's initial state so day one
 * looks identical to what the app already served; it is never imported by any runtime code path.
 *
 * Regenerated by walking every valid combination through the old resolution functions and image
 * lookup tables before they were deleted — not retyped by hand, so it can't have transcription
 * errors relative to what was actually live.
 */
export interface TiffinDishSeedRow {
  tier: TiffinMealTier;
  dietType: TiffinDietType;
  mealType: SingleMealType;
  dayOfWeek: DayOfWeek;
  dishName: string;
  /** Resolved to a full URL (via seed.ts's own tiffinImageUrl helper) at seed time. */
  imageSlug: string;
  hasAddOns: boolean;
  riceSubstitute: "rice" | "pulao";
  extraAddOnName?: string;
}

export const TIFFIN_DISH_SEED_DATA: TiffinDishSeedRow[] = [
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Sandwich", imageSlug: "sandwich", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Upma", imageSlug: "upma", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Poha", imageSlug: "poha", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Puri with Chole & Achar", imageSlug: "puri-chola", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Sandwich", imageSlug: "sandwich", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Bread Omelette", imageSlug: "bread-omelete", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Poha", imageSlug: "poha", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Puri with Chole & Achar", imageSlug: "puri-chola", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Fish Curry", imageSlug: "fish-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Fish piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Egg Curry", imageSlug: "egg-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Chicken Curry", imageSlug: "chicken-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "regular", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Dum Aloo", imageSlug: "dum-aloo-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo-mini", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Egg Curry", imageSlug: "egg-curry-mini", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "mini", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Chicken Curry", imageSlug: "chicken-curry-mini", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Sandwich", imageSlug: "sandwich", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Upma", imageSlug: "upma", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Poha", imageSlug: "poha", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Idli / Dosa with Sambar & Chutney", imageSlug: "idli-with-sambar-and-chutney", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Paneer Butter Masala", imageSlug: "paneer-butter-masala-and-pulao", hasAddOns: true, riceSubstitute: "pulao" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Matar Paneer", imageSlug: "matar-paneer", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Matar Chole", imageSlug: "matar-chole", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Puri with Chole", imageSlug: "puri-chola", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Monday", dishName: "Masala Pasta", imageSlug: "masala-pasta", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Tuesday", dishName: "Sandwich", imageSlug: "sandwich", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Wednesday", dishName: "Bread Omelette", imageSlug: "bread-omelete", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Thursday", dishName: "Aloo Paratha with Curd & Achar", imageSlug: "aloo-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Friday", dishName: "Poha", imageSlug: "poha", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Saturday", dishName: "Sattu Paratha with Curd & Achar", imageSlug: "sattu-paratha-with-dahi-and-achar", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "breakfast", dayOfWeek: "Sunday", dishName: "Idli / Dosa with Sambar & Chutney", imageSlug: "idli-with-sambar-and-chutney", hasAddOns: false, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Monday", dishName: "Aloo Matar", imageSlug: "aloo-matar", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Tuesday", dishName: "Aloo Parwal", imageSlug: "aloo-parwal", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Wednesday", dishName: "Aloo Soyabean", imageSlug: "aloo-soyabean", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Thursday", dishName: "Mushroom Masala", imageSlug: "mushroom-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Friday", dishName: "Rajma", imageSlug: "rajma", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Saturday", dishName: "Aloo Gobhi", imageSlug: "aloo-gobhi", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "lunch", dayOfWeek: "Sunday", dishName: "Mutton Curry", imageSlug: "mutton-and-pulao", hasAddOns: true, riceSubstitute: "pulao", extraAddOnName: "Mutton piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Monday", dishName: "Fish Curry", imageSlug: "fish-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Fish piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Tuesday", dishName: "Lauki Masala", imageSlug: "lauki-masala", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Wednesday", dishName: "Egg Curry", imageSlug: "egg-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Egg piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Thursday", dishName: "Dum Aloo", imageSlug: "dum-aloo", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Friday", dishName: "Chicken Curry", imageSlug: "chicken-curry", hasAddOns: true, riceSubstitute: "rice", extraAddOnName: "Chicken piece" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Saturday", dishName: "Matar Mushroom", imageSlug: "matar-mushroom", hasAddOns: true, riceSubstitute: "rice" },
  { tier: "premium", dietType: "non-veg", mealType: "dinner", dayOfWeek: "Sunday", dishName: "Puri with Chole", imageSlug: "puri-chola", hasAddOns: false, riceSubstitute: "rice" },
];

/** The named add-ons' shared flat prices — same value wherever the add-on is offered. */
export const TIFFIN_ADD_ON_PRICE_SEED_DATA: { name: string; price: number }[] = [
  { name: "Rice", price: 20 },
  { name: "Roti", price: 10 },
  { name: "Daal", price: 20 },
  { name: "Paratha", price: 15 },
  { name: "Pulao", price: 25 },
  { name: "Fish piece", price: 45 },
  { name: "Egg piece", price: 15 },
  { name: "Chicken piece", price: 40 },
  { name: "Mutton piece", price: 60 },
  // Generic "top up the same veg dish" add-on — its display name is synthesized per-dish at
  // resolution time as "Extra {dishName}"; this row just holds its shared flat price.
  { name: "Extra Portion", price: 30 },
];
